name: The ultimate Stabat Mater site
title: The ultimate Stabat Mater site
url: "https://mrnspam.github.io"
baseurl: "/stabmat-redo"
description: >-
  Search our Stabat Mater Collection: 300 compositions, composers, texts and 24 translations of the original Latin poem Stabat Mater Dolorosa.
markdown: kramdown
highlighter: rouge
permalink: pretty
collections:
  posts:
    output: true
  composers:
    output: true
    permalink: /composers/:slug/
sass:
  sass_dir: assets/css
  style: compressed
